server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: mq-p
  #配置rabbitMq 服务器
  rabbitmq:
    host: rabbit
    port: 5672
    username: admin
    password: admin
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost
    publisher-confirm-type: correlated
    publisher-returns: true